name: ip_location
description: A macOS Menu Bar application displaying information about the device's current ip address.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0 < 4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  connectivity_plus:
  flutter_riverpod:
  riverpod_annotation:
  gap:
  ip_geolocation_io:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  arb_generator:
  build_runner:
  riverpod_generator:
  riverpod_lint:
  app_store_screenshots:
    git:
      url: https://github.com/defuncart/app_store_screenshots
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  generate: true

arb_generator:
  input_filepath: "assets_dev/loca/loca.csv"
  output_directory: "assets_dev/l10n"
  filename_prepend: ""
  csv_settings:
    delimiter: ";"
    base_index: 1

flutter_launcher_icons:
  macos:
    generate: true
    image_path: "assets_dev/app_icons/app_icon_macos.png"
